targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/API/districts.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/queries/districts.graphql




          custom_parser_import: 'package:lambdastarter/graphql/utils/coercers.dart'
          scalar_mapping:
            - graphql_type: Time
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: ID
              dart_type: int
              use_custom_parser: false