name: ubengineering
description: lambda-flutter-starter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lambda:
    path: ../../flutter
  connectivity: ^3.0.2
  jiffy: ^4.1.0
  package_info: ^2.0.2
  device_info: ^2.0.2
  flutter_inner_drawer: ^1.0.0+1
  shared_preferences: ^2.0.4
  flutter_secure_storage: ^4.1.0
  url_launcher: ^6.0.2
  get: ^4.1.4
  local_auth: ^1.1.6
  cupertino_icons: ^1.0.3
  location: ^2.5.4
  firebase_messaging: ^10.0.0
  firebase_core: ^1.0.1
  nb_utils: ^4.0.9
  dio: ^4.0.0
  path_provider: ^2.0.0
  geolocator: ^7.0.3
  flutter_map: ^0.13.1
  flutter_slider_drawer: ^2.0.0
  fluttertoast: ^8.0.7
# Graphql dependency start
  json_annotation: ^4.0.1
  equatable: ^2.0.3
  meta: ^1.3.0
  gql: ^0.13.0
# Graphql dependency end
dev_dependencies:
  flutter_test:
    sdk: flutter
# Graphql dependency start
  artemis: ^7.1.0-beta.0
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
# Graphql dependency end
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lambda-logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/ub_logo.png
    - assets/images/ub2.png
    - assets/images/user_profile.png
    - assets/images/user.png
    - assets/images/setting.png
    - assets/images/request.png
    - assets/images/exit.png
    - assets/images/userReg.png


  fonts:
    - family: Roboto-Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
    - family: EsriIcons
      fonts:
        - asset: assets/fonts/Esri/EsriIcons.ttf
          weight: 400
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
