/// Flutter icons EsriIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EsriIcons
///      fonts:
///       - asset: fonts/EsriIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EsriIcons {
  EsriIcons._();

  static const _kFontFam = 'EsriIcons';
  static const IconData feature_layer = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData navigation = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData pan = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData zoom_in_magnifying_glass = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData non_visible = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData description = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData link_vertical = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData volume_on = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData overview_arrow_bottom_right = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData overview_arrow_top_left = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData overview_arrow_top_right = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData maximize = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData minimize = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData checkbox_unchecked = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData link_external = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData checkbox_checked = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData radio_unchecked = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData radio_checked = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData table = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData beginning = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData reverse = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData end = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData layer_list = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData basemap = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData applications = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData arrow_up_circled = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData arrow_down_circled = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData dock_bottom = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData arrow_left_circled = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData arrow_right_circled = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData minus_circled = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData drag_horizontal = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData close_circled = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData browser = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData configure_popup = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData contact = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData launch_link_external = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData dashboard = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData directions = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData directions2 = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData documentation = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData duplicate = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData review = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData environment_settings = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData error = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData grant = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData labels = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData left_arrow = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData loading_indicator = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData maps = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData marketplace = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData media = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData media2 = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData pie_chart = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData line_chart = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData question = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData resend_invitation = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData rotate = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData settings2 = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData sign_out = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData support = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData time_clock = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData zoom_out_magnifying_glass = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData locked = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData unlocked = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData favorites = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData dock_left = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData dock_right = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData organization = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData north_navigation = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData locate_circled = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData dial = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData polygon = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData unlocked_link_vertical = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData link_horizontal = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData unlocked_link_horizontal = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData swap = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData cta_link_external = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData reply = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData public = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData rotate_back = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData pan2 = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData tracking = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData expand2 = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData hollow_eye = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData up_arrow_circled = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData down_arrow_circled = const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData erase = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData up_down_arrows = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData plus_circled = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData add_attachment = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData error2 = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData experimental = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData mobile = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData polyline = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData visible = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData play_circled = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData volume_off = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData drag_vertical = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData handle_horizontal = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData handle_vertical = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData check_mark = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData left_triangle_arrow = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData right_triangle_arrow = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData down_arrow = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData up_arrow = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData overview_arrow_bottom_left = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData left_arrow_circled = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData right_arrow_circled = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData zoom_out_fixed = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData zoom_in_fixed = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData authorize = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData map_pin = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData blank_map_pin = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData announcement = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData notice_round = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData notice_triangle = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData locate = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData expand = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData collapse = const IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData attachment = const IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData deny = const IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData right_arrow = const IconData(0xe89e, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xe89f, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData share2 = const IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData collection = const IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData lightbulb = const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData sketch_rectangle = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData north_navigation_filled = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData default_action = const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData undo = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData redo = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData cursor = const IconData(0xe907, fontFamily: _kFontFam);
}
